language: java

dist: xenial

jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -U -V -q

### deployment disabled
# before_install:
#   - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
#   - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

notifications:
    email:
        on_success: never
        on_failure: never
    slack:
        on_failure: change
        on_success: change
        rooms:
            - openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#build
            #- openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#org.eclipse.smarthome.binding.bco
